## ULTIMO RASCUNHO ANTES DE FAZER O COMMIT INICIAL, ABAIXO ##
project:
  type: website
  preview:
    host: 0.0.0.0
    port: 7979  # 79 é o número periódico de ouro

website:
  title: "Projeto Dourados"

languages:
  pt:
    name: Português
    dir: pt
    default: true
  en:
    name: English
    dir: en

format:
  html:
    toc: true
    number-sections: false
    include-in-header: header.html
    theme: 
      light:
        - theme-light.scss
        - styles.scss
      dark:
        - darkly 
        - theme-dark.scss
        - styles.scss
    fontsize: 1.1em
    linestretch: 1.4
    number-depth: 3
